### ISSUE TITLE
Display list view in app

### ISSUE THREAD

**Issue by openHBP** [acdh-oeaw/acdh-django-zotero#2]
* acdh-django-zotero version: 0.1.3
* Django version: 2.2.6
* Python version: 3.6.7
* Operating System: LINUX Ubuntu 18.04.3 LTS

### Description
How can I display zotitems list in my app? It works fine in admin.py while using the 'router.register' functionality but I don't find a nice way to do it in my view.

### What I Did
I've tried the following url pattern in myapp/url.py

```python
urlpatterns = urlpatterns + [
    path("zotitems", ZotItemViewSet.as_view({'get': 'list'}), name='mybib')
]
```
But I get the following error message:

*Exception Value: | Could not resolve URL for hyperlinked relationship using view name "zotitem-detail". You may have failed to include the related model in your API, or incorrectly configured the `lookup_field` attribute on this field.*

Where and how do I do this? Is it a functionality of django-autocomplete, serializer, zotero?

**Comment by csae8092** [comment]
The app doesn't ship any views for ZotItems except a django-autocomplete endpoint and a default drf-api because the idea was that other classes only refer to a ZotItem by M2M or FK relation.

Any curation/publication of Zotero Items should happen directly in Zotero

Anyway, thanks for your interest in this little app, though I am afraid it is not very well documented and maintained. The most recent project I used the app (or its main functionalities) is [IAD](https://github.com/acdh-oeaw/iad). Maybe you'll find some useful code here.
